package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 *ComprobantePagoo generated by hbm2java
 */
public class ComprobantePago  implements java.io.Serializable {


     private int nrocomprobante;
     private Licencia licencia;
     private UsuarioGeneral usuariogeneral;
     private Date fechahoracomprobante;
     private double montototal;
     private Set conceptocomprobantes = new HashSet(0);

    public ComprobantePago() {
    }

	
    public ComprobantePago(int nrocomprobante, Licencia licencia, UsuarioGeneral usuariogeneral, Date fechahoracomprobante, double montototal) {
        this.nrocomprobante = nrocomprobante;
        this.licencia = licencia;
        this.usuariogeneral = usuariogeneral;
        this.fechahoracomprobante = fechahoracomprobante;
        this.montototal = montototal;
    }
    public ComprobantePago(int nrocomprobante, Licencia licencia, UsuarioGeneral usuariogeneral, Date fechahoracomprobante, double montototal, Set conceptocomprobantes) {
       this.nrocomprobante = nrocomprobante;
       this.licencia = licencia;
       this.usuariogeneral = usuariogeneral;
       this.fechahoracomprobante = fechahoracomprobante;
       this.montototal = montototal;
       this.conceptocomprobantes = conceptocomprobantes;
    }
   
    public int getNrocomprobante() {
        return this.nrocomprobante;
    }
    
    public void setNrocomprobante(int nrocomprobante) {
        this.nrocomprobante = nrocomprobante;
    }
    public Licencia getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Licencia licencia) {
        this.licencia = licencia;
    }
    public UsuarioGeneral getUsuariogeneral() {
        return this.usuariogeneral;
    }
    
    public void setUsuariogeneral(UsuarioGeneral usuariogeneral) {
        this.usuariogeneral = usuariogeneral;
    }
    public Date getFechahoracomprobante() {
        return this.fechahoracomprobante;
    }
    
    public void setFechahoracomprobante(Date fechahoracomprobante) {
        this.fechahoracomprobante = fechahoracomprobante;
    }
    public double getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(double montototal) {
        this.montototal = montototal;
    }
    public Set getConceptocomprobantes() {
        return this.conceptocomprobantes;
    }
    
    public void setConceptocomprobantes(Set conceptocomprobantes) {
        this.conceptocomprobantes = conceptocomprobantes;
    }




}


