package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1



/**
 * ConceptoComprobante generated by hbm2java
 */
public class ConceptoComprobante  implements java.io.Serializable {


     private int idconcepto;
     private ComprobantePago comprobantepago;
     private String nombreconcepto;
     private double monto;

    public ConceptoComprobante() {
    }

    public ConceptoComprobante(int idconcepto, ComprobantePago comprobantepago, String nombreconcepto, double monto) {
       this.idconcepto = idconcepto;
       this.comprobantepago = comprobantepago;
       this.nombreconcepto = nombreconcepto;
       this.monto = monto;
    }
   
    public int getIdconcepto() {
        return this.idconcepto;
    }
    
    public void setIdconcepto(int idconcepto) {
        this.idconcepto = idconcepto;
    }
    public ComprobantePago getComprobantepago() {
        return this.comprobantepago;
    }
    
    public void setComprobantepago(ComprobantePago comprobantepago) {
        this.comprobantepago = comprobantepago;
    }
    public String getNombreconcepto() {
        return this.nombreconcepto;
    }
    
    public void setNombreconcepto(String nombreconcepto) {
        this.nombreconcepto = nombreconcepto;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }




}


