package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *CopiaLicenciaa generated by hbm2java
 */
public class CopiaLicencia  implements java.io.Serializable {


     private CopiaLicenciaId id;
     private Licencia licencia;
     private UsuarioGeneral usuariogeneral;
     private String motivoSolicitud;
     private Date fechacopia;

    public CopiaLicencia() {
    }

    public CopiaLicencia(CopiaLicenciaId id, Licencia licencia, UsuarioGeneral usuariogeneral, String motivoSolicitud, Date fechacopia) {
       this.id = id;
       this.licencia = licencia;
       this.usuariogeneral = usuariogeneral;
       this.motivoSolicitud = motivoSolicitud;
       this.fechacopia = fechacopia;
    }
   
    public CopiaLicenciaId getId() {
        return this.id;
    }
    
    public void setId(CopiaLicenciaId id) {
        this.id = id;
    }
    public Licencia getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Licencia licencia) {
        this.licencia = licencia;
    }
    public UsuarioGeneral getUsuariogeneral() {
        return this.usuariogeneral;
    }
    
    public void setUsuariogeneral(UsuarioGeneral usuariogeneral) {
        this.usuariogeneral = usuariogeneral;
    }
    public String getMotivoSolicitud() {
        return this.motivoSolicitud;
    }
    
    public void setMotivoSolicitud(String motivoSolicitud) {
        this.motivoSolicitud = motivoSolicitud;
    }
    public Date getFechacopia() {
        return this.fechacopia;
    }
    
    public void setFechacopia(Date fechacopia) {
        this.fechacopia = fechacopia;
    }




}


