package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1



/**
 * CopiaLicenciaId generated by hbm2java
 */
public class CopiaLicenciaId  implements java.io.Serializable {


     private int idlicencia;
     private int nrocopia;

    public CopiaLicenciaId() {
    }

    public CopiaLicenciaId(int idlicencia, int nrocopia) {
       this.idlicencia = idlicencia;
       this.nrocopia = nrocopia;
    }
   
    public int getIdlicencia() {
        return this.idlicencia;
    }
    
    public void setIdlicencia(int idlicencia) {
        this.idlicencia = idlicencia;
    }
    public int getNrocopia() {
        return this.nrocopia;
    }
    
    public void setNrocopia(int nrocopia) {
        this.nrocopia = nrocopia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CopiaLicenciaId) ) return false;
		 CopiaLicenciaId castOther = ( CopiaLicenciaId ) other; 
         
		 return (this.getIdlicencia()==castOther.getIdlicencia())
 && (this.getNrocopia()==castOther.getNrocopia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdlicencia();
         result = 37 * result + this.getNrocopia();
         return result;
   }   


}


