package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Licencia generated by hbm2java
 */
public class Licencia  implements java.io.Serializable {


     private int idlicencia;
     private Titular titular;
     private UsuarioGeneral usuariogeneral;
     private int nrolicencia;
     private Date fechaotorgamiento;
     private Date fechavencimiento;
     private String categoria;
     private Byte vigente;
     private Set copialicencias = new HashSet(0);
     private Set comprobantepagos = new HashSet(0);

    public Licencia() {
    }

	
    public Licencia(int idlicencia, Titular titular,UsuarioGeneral usuariogeneral, int nrolicencia, Date fechaotorgamiento, Date fechavencimiento, String categoria) {
        this.idlicencia = idlicencia;
        this.titular = titular;
        this.usuariogeneral = usuariogeneral;
        this.nrolicencia = nrolicencia;
        this.fechaotorgamiento = fechaotorgamiento;
        this.fechavencimiento = fechavencimiento;
        this.categoria = categoria;
    }
    public Licencia(int idlicencia, Titular titular,UsuarioGeneral usuariogeneral, int nrolicencia, Date fechaotorgamiento, Date fechavencimiento, String categoria, Byte vigente, Set copialicencias, Set comprobantepagos) {
       this.idlicencia = idlicencia;
       this.titular = titular;
       this.usuariogeneral = usuariogeneral;
       this.nrolicencia = nrolicencia;
       this.fechaotorgamiento = fechaotorgamiento;
       this.fechavencimiento = fechavencimiento;
       this.categoria = categoria;
       this.vigente = vigente;
       this.copialicencias = copialicencias;
       this.comprobantepagos = comprobantepagos;
    }
   
    public int getIdlicencia() {
        return this.idlicencia;
    }
    
    public void setIdlicencia(int idlicencia) {
        this.idlicencia = idlicencia;
    }
    public Titular getTitular() {
        return this.titular;
    }
    
    public void setTitular(Titular titular) {
        this.titular = titular;
    }
    public UsuarioGeneral getUsuariogeneral() {
        return this.usuariogeneral;
    }
    
    public void setUsuariogeneral (UsuarioGeneral usuariogeneral) {
        this.usuariogeneral = usuariogeneral;
    }
    public int getNrolicencia() {
        return this.nrolicencia;
    }
    
    public void setNrolicencia(int nrolicencia) {
        this.nrolicencia = nrolicencia;
    }
    public Date getFechaotorgamiento() {
        return this.fechaotorgamiento;
    }
    
    public void setFechaotorgamiento(Date fechaotorgamiento) {
        this.fechaotorgamiento = fechaotorgamiento;
    }
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Byte getVigente() {
        return this.vigente;
    }
    
    public void setVigente(Byte vigente) {
        this.vigente = vigente;
    }
    public Set getCopialicencias() {
        return this.copialicencias;
    }
    
    public void setCopialicencias(Set copialicencias) {
        this.copialicencias = copialicencias;
    }
    public Set getComprobantepagos() {
        return this.comprobantepagos;
    }
    
    public void setComprobantepagos(Set comprobantepagos) {
        this.comprobantepagos = comprobantepagos;
    }




}


