package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1



/**
 * ModificacionTitular generated by hbm2java
 */
public class ModificacionTitular  implements java.io.Serializable {


     private ModificacionTitularId id;
     private Titular titular;
     private UsuarioGeneral usuariogeneral;
     private String motivo;

    public ModificacionTitular() {
    }

    public ModificacionTitular(ModificacionTitularId id, Titular titular, UsuarioGeneral usuariogeneral, String motivo) {
       this.id = id;
       this.titular = titular;
       this.usuariogeneral = usuariogeneral;
       this.motivo = motivo;
    }
   
    public ModificacionTitularId getId() {
        return this.id;
    }
    
    public void setId(ModificacionTitularId id) {
        this.id = id;
    }
    public Titular getTitular() {
        return this.titular;
    }
    
    public void setTitular(Titular titular) {
        this.titular = titular;
    }
    public UsuarioGeneral getUsuariogeneral() {
        return this.usuariogeneral;
    }
    
    public void setUsuariogeneral(UsuarioGeneral usuariogeneral) {
        this.usuariogeneral = usuariogeneral;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


