package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1



/**
 * ModificacionBajaUsuario generated by hbm2java
 */
public class ModificacionBajaUsuario  implements java.io.Serializable {


     private ModificacionBajaUsuarioId id;
     private Administrador administrador;
     private Usuario usuario;
     private String motivo;

    public ModificacionBajaUsuario() {
    }

    public ModificacionBajaUsuario(ModificacionBajaUsuarioId id, Administrador administrador, Usuario usuario, String motivo) {
       this.id = id;
       this.administrador = administrador;
       this.usuario = usuario;
       this.motivo = motivo;
    }
   
    public ModificacionBajaUsuarioId getId() {
        return this.id;
    }
    
    public void setId(ModificacionBajaUsuarioId id) {
        this.id = id;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


