package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *ModificacionTitularIdd generated by hbm2java
 */
public class ModificacionTitularId  implements java.io.Serializable {


     private int idtitularmodificado;
     private String usermodificacion;
     private Date fechahoramodificacion;

    public ModificacionTitularId() {
    }

    public ModificacionTitularId(int idtitularmodificado, String usermodificacion, Date fechahoramodificacion) {
       this.idtitularmodificado = idtitularmodificado;
       this.usermodificacion = usermodificacion;
       this.fechahoramodificacion = fechahoramodificacion;
    }
   
    public int getIdtitularmodificado() {
        return this.idtitularmodificado;
    }
    
    public void setIdtitularmodificado(int idtitularmodificado) {
        this.idtitularmodificado = idtitularmodificado;
    }
    public String getUsermodificacion() {
        return this.usermodificacion;
    }
    
    public void setUsermodificacion(String usermodificacion) {
        this.usermodificacion = usermodificacion;
    }
    public Date getFechahoramodificacion() {
        return this.fechahoramodificacion;
    }
    
    public void setFechahoramodificacion(Date fechahoramodificacion) {
        this.fechahoramodificacion = fechahoramodificacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModificacionTitularId) ) return false;
		ModificacionTitularId castOther = (ModificacionTitularId ) other; 
         
		 return (this.getIdtitularmodificado()==castOther.getIdtitularmodificado())
 && ( (this.getUsermodificacion()==castOther.getUsermodificacion()) || ( this.getUsermodificacion()!=null && castOther.getUsermodificacion()!=null && this.getUsermodificacion().equals(castOther.getUsermodificacion()) ) )
 && ( (this.getFechahoramodificacion()==castOther.getFechahoramodificacion()) || ( this.getFechahoramodificacion()!=null && castOther.getFechahoramodificacion()!=null && this.getFechahoramodificacion().equals(castOther.getFechahoramodificacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdtitularmodificado();
         result = 37 * result + ( getUsermodificacion() == null ? 0 : this.getUsermodificacion().hashCode() );
         result = 37 * result + ( getFechahoramodificacion() == null ? 0 : this.getFechahoramodificacion().hashCode() );
         return result;
   }   


}


