package Entidades;
// Generated 15/10/2018 18:54:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Titular generated by hbm2java
 */
public class Titular  implements java.io.Serializable {


     private int idtitular;
     private UsuarioGeneral usuariogeneral;
     private int dni;
     private String tipodni;
     private String cuil;
     private String apellido;
     private String nombre;
     private Date fechanacimiento;
     private String sexo;
     private String domicilio;
     private String nacionalidad;
     private String grupofactorsanguineo;
     private Byte donante;
     private String observaciones;
     private Date fechacreacion;
     private Byte activo;
     private Set modificaciontitulars = new HashSet(0);
     private Set licencias = new HashSet(0);

    public Titular() {
    }

	
    public Titular(int idtitular,UsuarioGeneral usuariogeneral, int dni, String tipodni, String cuil, String apellido, String nombre, Date fechanacimiento, String sexo, String domicilio, String nacionalidad, String grupofactorsanguineo, String observaciones, Date fechacreacion) {
        this.idtitular = idtitular;
        this.usuariogeneral = usuariogeneral;
        this.dni = dni;
        this.tipodni = tipodni;
        this.cuil = cuil;
        this.apellido = apellido;
        this.nombre = nombre;
        this.fechanacimiento = fechanacimiento;
        this.sexo = sexo;
        this.domicilio = domicilio;
        this.nacionalidad = nacionalidad;
        this.grupofactorsanguineo = grupofactorsanguineo;
        this.observaciones = observaciones;
        this.fechacreacion = fechacreacion;
    }
    public Titular(int idtitular,UsuarioGeneral usuariogeneral, int dni, String tipodni, String cuil, String apellido, String nombre, Date fechanacimiento, String sexo, String domicilio, String nacionalidad, String grupofactorsanguineo, Byte donante, String observaciones, Date fechacreacion, Byte activo, Set modificaciontitulars, Set licencias) {
       this.idtitular = idtitular;
       this.usuariogeneral = usuariogeneral;
       this.dni = dni;
       this.tipodni = tipodni;
       this.cuil = cuil;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechanacimiento = fechanacimiento;
       this.sexo = sexo;
       this.domicilio = domicilio;
       this.nacionalidad = nacionalidad;
       this.grupofactorsanguineo = grupofactorsanguineo;
       this.donante = donante;
       this.observaciones = observaciones;
       this.fechacreacion = fechacreacion;
       this.activo = activo;
       this.modificaciontitulars = modificaciontitulars;
       this.licencias = licencias;
    }
   
    public int getIdtitular() {
        return this.idtitular;
    }
    
    public void setIdtitular(int idtitular) {
        this.idtitular = idtitular;
    }
    public UsuarioGeneral getUsuariogeneral() {
        return this.usuariogeneral;
    }
    
    public void setUsuariogeneral (UsuarioGeneral usuariogeneral) {
        this.usuariogeneral = usuariogeneral;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getTipodni() {
        return this.tipodni;
    }
    
    public void setTipodni(String tipodni) {
        this.tipodni = tipodni;
    }
    public String getCuil() {
        return this.cuil;
    }
    
    public void setCuil(String cuil) {
        this.cuil = cuil;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getGrupofactorsanguineo() {
        return this.grupofactorsanguineo;
    }
    
    public void setGrupofactorsanguineo(String grupofactorsanguineo) {
        this.grupofactorsanguineo = grupofactorsanguineo;
    }
    public Byte getDonante() {
        return this.donante;
    }
    
    public void setDonante(Byte donante) {
        this.donante = donante;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(Byte activo) {
        this.activo = activo;
    }
    public Set getModificaciontitulars() {
        return this.modificaciontitulars;
    }
    
    public void setModificaciontitulars(Set modificaciontitulars) {
        this.modificaciontitulars = modificaciontitulars;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


