/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Gestores.GestorTitular;
import Entidades.*;
import Persistencia.TitularDAO;
import Gestores.GestorValidacion;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.System.exit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author L. Nudel
 */
public class AltaTitular extends javax.swing.JPanel {

    private File imagenFile;

    public File getImagenFile() {
        return imagenFile;
    }

    public void setImagenFile(File imagenFile) {
        this.imagenFile = imagenFile;
    }
    
    /**
     * Creates new form RegistrarBedel
     */
    public AltaTitular() {
        initComponents();
        ImageIcon imageIcon = new ImageIcon("src/Images/profile-default.jpg");// load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back
        this.jLabelPic.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDonante = new javax.swing.ButtonGroup();
        jLabelTipoDNI = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelRegistrarBedel = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonAtras = new javax.swing.JButton();
        jComboBoxTipoDNI = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNumDNI = new javax.swing.JLabel();
        jTextFieldNumeroDNI = new javax.swing.JTextField();
        jLabelCUIL = new javax.swing.JLabel();
        jTextFieldCUIL = new javax.swing.JTextField();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelGrupoFactor = new javax.swing.JLabel();
        jComboBoxGrupoFactor = new javax.swing.JComboBox<>();
        jLabelDonante = new javax.swing.JLabel();
        jRadioButtonDonanteSi = new javax.swing.JRadioButton();
        jRadioButtonDonanteNo = new javax.swing.JRadioButton();
        jLabelObservaciones = new javax.swing.JLabel();
        jTextFieldObservaciones = new javax.swing.JTextField();
        jLabelFoto = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonSeleccionFoto = new javax.swing.JButton();
        jLabelPic = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 300), new java.awt.Dimension(0, 300), new java.awt.Dimension(32767, 300));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 32767));

        jLabelTipoDNI.setText("Tipo de DNI ------------------>");
        jLabelTipoDNI.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jLabelApellido.setText("Apellido ---------------------->");
        jLabelApellido.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jLabelRegistrarBedel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegistrarBedel.setText("Registrar Titular");

        jTextFieldNombre.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");
        jTextFieldNombre.setNextFocusableComponent(jTextFieldFechaNacimiento);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldApellido.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");
        jTextFieldApellido.setNextFocusableComponent(jTextFieldNombre);

        jButtonAtras.setText("Atras");
        jButtonAtras.setToolTipText("Para regresar al menú anterior.");
        jButtonAtras.setNextFocusableComponent(jComboBoxTipoDNI);
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jComboBoxTipoDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DU", "LE", "LC", "OTRO" }));
        jComboBoxTipoDNI.setToolTipText("DU (Documento Único), LE (Libreta de Enrolamiento), LC (Libreta Cívica), OTRO");
        jComboBoxTipoDNI.setNextFocusableComponent(jTextFieldNumeroDNI);
        jComboBoxTipoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDNIActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre ---------------------->");
        jLabelNombre.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jLabelNumDNI.setText("Número de DNI ------------->");
        jLabelNumDNI.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jTextFieldNumeroDNI.setToolTipText("Número de documento. Ejemplo: 11222333.");
        jTextFieldNumeroDNI.setNextFocusableComponent(jTextFieldCUIL);
        jTextFieldNumeroDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroDNIActionPerformed(evt);
            }
        });

        jLabelCUIL.setText("CUIL --------------------------->");
        jLabelCUIL.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jTextFieldCUIL.setToolTipText("Número de CUIL (sin guiones). Ejemplo: 22112223338.");
        jTextFieldCUIL.setNextFocusableComponent(jTextFieldApellido);
        jTextFieldCUIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCUILActionPerformed(evt);
            }
        });

        jLabelFechaNacimiento.setText("Fecha de nacimiento ---->");
        jLabelFechaNacimiento.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jTextFieldFechaNacimiento.setToolTipText("Fecha de nacimiento con formato dd-MM-yyyy.");
        jTextFieldFechaNacimiento.setNextFocusableComponent(jComboBoxSexo);
        jTextFieldFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacimientoActionPerformed(evt);
            }
        });

        jLabelSexo.setText("Sexo -------------------------->");
        jLabelSexo.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboBoxSexo.setToolTipText("Sexo de la persona: M (masculino) y F (femenino).");
        jComboBoxSexo.setNextFocusableComponent(jTextFieldDomicilio);

        jLabelDomicilio.setText("Domicilio -------------------->");
        jLabelDomicilio.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jTextFieldNacionalidad.setToolTipText("Nacionalidad de la persona. Ejemplo: Argentino.");
        jTextFieldNacionalidad.setNextFocusableComponent(jComboBoxGrupoFactor);
        jTextFieldNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNacionalidadActionPerformed(evt);
            }
        });

        jLabelNacionalidad.setText("Nacionalidad --------------->");
        jLabelNacionalidad.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jTextFieldDomicilio.setToolTipText("Domicilio de la persona. Ejemplo: Lavaisse 610.");
        jTextFieldDomicilio.setNextFocusableComponent(jTextFieldNacionalidad);
        jTextFieldDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDomicilioActionPerformed(evt);
            }
        });

        jLabelGrupoFactor.setText("Grupo y Factor Sanguíneo");
        jLabelGrupoFactor.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jComboBoxGrupoFactor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0+", "0-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jComboBoxGrupoFactor.setToolTipText("Grupo y factor sanguíneo de la persona.");
        jComboBoxGrupoFactor.setNextFocusableComponent(jRadioButtonDonanteSi);
        jComboBoxGrupoFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrupoFactorActionPerformed(evt);
            }
        });

        jLabelDonante.setText("Donante ---------------------------------->");
        jLabelDonante.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        buttonGroupDonante.add(jRadioButtonDonanteSi);
        jRadioButtonDonanteSi.setText("SI");
        jRadioButtonDonanteSi.setToolTipText("SI: la persona ES donante.");
        jRadioButtonDonanteSi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonDonanteSi.setNextFocusableComponent(jRadioButtonDonanteNo);
        jRadioButtonDonanteSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDonanteSiActionPerformed(evt);
            }
        });

        buttonGroupDonante.add(jRadioButtonDonanteNo);
        jRadioButtonDonanteNo.setText("NO");
        jRadioButtonDonanteNo.setToolTipText("NO: la persona NO ES donante.");
        jRadioButtonDonanteNo.setNextFocusableComponent(jTextFieldObservaciones);
        jRadioButtonDonanteNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDonanteNoActionPerformed(evt);
            }
        });

        jLabelObservaciones.setText("Observaciones");
        jLabelObservaciones.setToolTipText("2 a 32 caracteres. Mayúsculas, minúsculas y números.");

        jTextFieldObservaciones.setToolTipText("Observaciones. Ejemplo: \"Usa anteojos y/o lentes de contacto\".");
        jTextFieldObservaciones.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jTextFieldObservaciones.setNextFocusableComponent(jButtonSeleccionFoto);
        jTextFieldObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservacionesActionPerformed(evt);
            }
        });

        jLabelFoto.setText("Foto");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("Validar los campos y dar de alta al Titular.");
        jButtonAceptar.setNextFocusableComponent(jButtonAtras);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonSeleccionFoto.setText("Seleccionar foto");
        jButtonSeleccionFoto.setToolTipText("Abre el navegador de archivos para seleccionar la foto del Titular.");
        jButtonSeleccionFoto.setNextFocusableComponent(jButtonAceptar);
        jButtonSeleccionFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionFotoActionPerformed(evt);
            }
        });

        jLabelPic.setBackground(new java.awt.Color(0, 255, 255));
        jLabelPic.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabelRegistrarBedel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabelDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButtonDonanteSi)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonDonanteNo))
                                        .addComponent(jLabelFechaNacimiento)
                                        .addComponent(jLabelSexo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelNumDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelCUIL)
                                                .addComponent(jLabelApellido)
                                                .addComponent(jLabelTipoDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(7, 7, 7)
                                                    .addComponent(jComboBoxTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextFieldCUIL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldNumeroDNI, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelGrupoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxGrupoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jButtonSeleccionFoto))
                                    .addComponent(jTextFieldObservaciones)
                                    .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrarBedel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelObservaciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNumDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCUIL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCUIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelGrupoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxGrupoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDonante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonDonanteSi)
                                    .addComponent(jRadioButtonDonanteNo))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonSeleccionFoto)
                                        .addGap(123, 123, 123))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelPic, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)))))
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonAtras))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
       VentanaPrincipal topFrame = (VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
        
       TipoDNIEnum tipoDNI = TipoDNIEnum.DU;
        switch (this.jComboBoxTipoDNI.getSelectedItem().toString()){
           case "DU": tipoDNI = TipoDNIEnum.DU; break;
           case "LE": tipoDNI = TipoDNIEnum.LE; break;
           case "LC": tipoDNI = TipoDNIEnum.LC; break;
           case "OTRO": tipoDNI = TipoDNIEnum.OTRO; break;
        }
       
        GrupoFactorSanguineoEnum grupofactorsang = GrupoFactorSanguineoEnum.Op;
        switch (this.jComboBoxGrupoFactor.getSelectedItem().toString()){
           case "0+": grupofactorsang = GrupoFactorSanguineoEnum.Op; break;
           case "0-": grupofactorsang = GrupoFactorSanguineoEnum.On; break;
           case "A+": grupofactorsang = GrupoFactorSanguineoEnum.Ap; break;
           case "A-": grupofactorsang = GrupoFactorSanguineoEnum.An; break;
           case "B+": grupofactorsang = GrupoFactorSanguineoEnum.Bp; break;
           case "B-": grupofactorsang = GrupoFactorSanguineoEnum.Bn; break;
           case "AB+": grupofactorsang = GrupoFactorSanguineoEnum.ABp; break;
           case "AB-": grupofactorsang = GrupoFactorSanguineoEnum.ABn; break;
        }
        
        SexoEnum sexo = SexoEnum.M;
        switch (this.jComboBoxSexo.getSelectedItem().toString()){
           case "M": sexo = SexoEnum.M; break;
           case "F": sexo = SexoEnum.F; break;
        }
        
       int numerodni = Integer.parseInt(jTextFieldNumeroDNI.getText());
       
       Date fechanacimiento = this.convertirStringADateFormatoFecha(this.jTextFieldFechaNacimiento.getText());
       
       String cuil=this.jTextFieldCUIL.getText(), nombre=this.jTextFieldNombre.getText(),
               apellido=this.jTextFieldApellido.getText(),
               domicilio=this.jTextFieldDomicilio.getText(),
               nacionalidad=this.jTextFieldNacionalidad.getText(),
               observaciones=this.jTextFieldObservaciones.getText();
       
       Byte donante = 0;
       if(this.jRadioButtonDonanteSi.isSelected())
           donante = 1;
       
       GestorTitular gestor = new GestorTitular();
       
       //Validacion de los campos:
       GestorValidacion gestorValidacion = new GestorValidacion();
       ArrayList<Integer> validacionCampos = gestorValidacion.validarCamposTitular(numerodni, cuil, fechanacimiento, nombre, apellido, domicilio, nacionalidad, observaciones);
       
       if(validacionCampos.contains(0)){
            if(validacionCampos.get(0)==0)
                topFrame.mensajeEmergente("Error de validación: número de documento", "No se admite campo vacío. Debe ingresar un número entero positivo de 7 u 8 cifras.");
            if(validacionCampos.get(1)==0)
                topFrame.mensajeEmergente("Error de validación: CUIL", "No se admite campo vacío. Debe ingresar el número de CUIL sin guiones.");
            if(validacionCampos.get(2)==0)
                topFrame.mensajeEmergente("Error de validación: apellido", "No se admite campo vacío. Tamaño máximo: 32 caracteres. Debe contener sólo letras (minúsculas o mayúsculas).");
            if(validacionCampos.get(3)==0)
                topFrame.mensajeEmergente("Error de validación: nombre", "No se admite campo vacío. Tamaño máximo: 32 caracteres. Debe contener sólo letras (minúsculas o mayúsculas).");
            if(validacionCampos.get(4)==0)
                topFrame.mensajeEmergente("Error de validación: fecha de nacimiento", "No se admite campo vacío. Debe tener el siguiente formato: DD-MM-YYYY. Por ejemplo: 01-15-1999 (15 de Enero de 1999).");
            if(validacionCampos.get(5)==0)
                topFrame.mensajeEmergente("Error de validación: domicilio", "No se admite campo vacío. Tamaño máximo: 100 caracteres.");
            if(validacionCampos.get(6)==0)
                topFrame.mensajeEmergente("Error de validación: nacionalidad", "No se admite campo vacío. Tamaño máximo: 32 caracteres.");
            if(validacionCampos.get(7)==0)
                topFrame.mensajeEmergente("Error de validación: obsevaciones", "Tamaño máximo: 300 caracteres.");
       }else{
            UsuarioGeneral usuariogeneral = topFrame.getUsuariogeneral();
            ArrayList<String> arregloAltaTitular = gestor.altaTitular(numerodni, tipoDNI, 
            cuil, nombre, apellido, fechanacimiento, sexo, domicilio,
            nacionalidad, grupofactorsang, donante, observaciones, usuariogeneral, imagenFile);
       
            if (arregloAltaTitular.isEmpty()){
                topFrame.mensajeEmergente("Registro Exitoso", "El Titular se registró correctamente.");
                jComboBoxTipoDNI.setSelectedIndex(0);
                jTextFieldNumeroDNI.setText("");
                jTextFieldCUIL.setText("");
                jTextFieldNombre.setText("");
                jTextFieldApellido.setText("");
                jTextFieldFechaNacimiento.setText("");
                jComboBoxSexo.setSelectedIndex(0);
                jTextFieldNacionalidad.setText("");
                jTextFieldDomicilio.setText("");
                jComboBoxGrupoFactor.setSelectedIndex(0);
                jRadioButtonDonanteNo.setSelected(true);
                jTextFieldObservaciones.setText("");
                ImageIcon imageIcon = new ImageIcon("src/Images/profile-default.jpg");// load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it 
                Image newimg = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
                imageIcon = new ImageIcon(newimg);  // transform it back
                this.jLabelPic.setIcon(imageIcon);
                
            }else{  
               topFrame.mensajeEmergente("CUIL asocioado a un Titular", "Apellido: "+arregloAltaTitular.get(1)+"\n.Nombre: "+arregloAltaTitular.get(2));
            }
        }   
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private Date convertirStringADateFormatoFecha(String fecha){
        Date date = null;
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        try {
            date = sdf.parse(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(AltaTitular.class.getName()).log(Level.SEVERE, null, ex);
        }
       return date;
    }
    
    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal topFrame = (VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
        
        ArrayList<JButton> botonesDialogo = new ArrayList<>();
        botonesDialogo = topFrame.mensajeEmergenteConfirmacion("Mensaje de Confirmación", "Al regresar al menú principal, los datos que haya ingresado en algún campo serán descartados.");
        JDialog dialogo = (JDialog) SwingUtilities.getWindowAncestor(botonesDialogo.get(0));
        
        botonesDialogo.get(0).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
            
           
            MenuAdministrador panelMenu = new MenuAdministrador();
            //panelMenu.setImage("/Imagenes/fondoabs.jpg");
            topFrame.add(panelMenu, BorderLayout.CENTER);
            this.setVisible(false);
            topFrame.remove(this);
            topFrame.setSize(500,500);             
        });
        
        botonesDialogo.get(1).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
        });
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jComboBoxTipoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDNIActionPerformed

    private void jTextFieldNumeroDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroDNIActionPerformed

    private void jTextFieldCUILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCUILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCUILActionPerformed

    private void jTextFieldFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacimientoActionPerformed

    private void jTextFieldNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNacionalidadActionPerformed

    private void jRadioButtonDonanteSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDonanteSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDonanteSiActionPerformed

    private void jRadioButtonDonanteNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDonanteNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDonanteNoActionPerformed

    private void jTextFieldObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacionesActionPerformed

    private void jTextFieldDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDomicilioActionPerformed

    private void jComboBoxGrupoFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrupoFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGrupoFactorActionPerformed

    private void jButtonSeleccionFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionFotoActionPerformed
        //jFileChooser
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
    
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("JPG, PNG & GIF Images", "jpg", "png", "gif"); 
        fileChooser.setFileFilter(imgFilter);

        int result = fileChooser.showOpenDialog(this);

        if (result != JFileChooser.CANCEL_OPTION) {

            File fileName = fileChooser.getSelectedFile();

            if ((fileName == null) || (fileName.getName().equals(""))) {
                VentanaPrincipal topFrame = (VentanaPrincipal) SwingUtilities.getWindowAncestor(this);
                topFrame.mensajeEmergente("ERROR", "No seleccionó un archivo. "
                     + "O el archivo seleccionado no corresponde a un formato válido");
            } else {
                this.imagenFile = fileName;
                String rutaImagen = fileName.getAbsolutePath();
                System.out.println(rutaImagen);
                //PONER LA IMAGEN EN EL jLabel.
                ImageIcon imageIcon = new ImageIcon(rutaImagen);// load the image to a imageIcon
                Image image = imageIcon.getImage(); // transform it 
                Image newimg = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
                imageIcon = new ImageIcon(newimg);  // transform it back
                this.jLabelPic.setIcon(imageIcon);
            }
        }
        fileChooser.setVisible(false);
        this.remove(fileChooser);
    }//GEN-LAST:event_jButtonSeleccionFotoActionPerformed

    
    //codigo de la imagen de fondo ----------------------------------------
    private Image fondo=null;
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(fondo,0,0,getWidth(),getHeight(),null);
    }
    
    public void setImage(String image){
        if (image!=null) {
            fondo=new ImageIcon(getClass().getResource(image)).getImage();
        }
    }
    //-----------------------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDonante;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonSeleccionFoto;
    private javax.swing.JComboBox<String> jComboBoxGrupoFactor;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTipoDNI;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCUIL;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelDonante;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelGrupoFactor;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumDNI;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelPic;
    private javax.swing.JLabel jLabelRegistrarBedel;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTipoDNI;
    private javax.swing.JRadioButton jRadioButtonDonanteNo;
    private javax.swing.JRadioButton jRadioButtonDonanteSi;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCUIL;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroDNI;
    private javax.swing.JTextField jTextFieldObservaciones;
    // End of variables declaration//GEN-END:variables
}
